#!/bin/bash

dir=$(readlink -f $(dirname $0)/../)

/usr/games/xboard -fcp "$dir/bin/weini --xboard"  -fd "$dir" -scp "/media/BK1/www/p/chessEngine/weini/other/galjoen_v0.38/engine/galjoen_eng"  -sd "/media/BK1/www/p/chessEngine/weini/other/galjoen_v0.38/engine" -tc 0:20 -mps 40 -ponder
#-debug

