#!/bin/bash

dir=$(readlink -f $(dirname $0)/../)

/usr/games/xboard -fcp "$dir/bin/weini --xboard"  -fd "$dir" -scp "$dir/other/arasan-21.0/bin/arasanx-64"  -sd "$dir/other/arasan-21.0/bin/" -tc 0:20 -mps 40 -ponder
#-debug

