#!/bin/bash

dir=$(readlink -f $(dirname $0)/../)

/usr/games/xboard -fcp "$dir/bin/weini --xboard"  -fd "$dir" -scp "/media/BK1/www/p/chessEngine/weini/other/isa/Linux/isa_linux64"  -sd "/media/BK1/www/p/chessEngine/weini/other/isa/Linux" -tc 1:00 -mps 40 -ponder
#-debug

