#!/bin/bash

dir=$(readlink -f $(dirname $0)/../)

/usr/games/xboard -fcp "$dir/bin/weini --xboard" -fd "$dir/bin" -scp "$dir/release/weini_0.0.23/weini_linux_gcc_6.3.0_popcnt_x64_0.0.23 --xboard" -sd "$dir/release/weini_0.0.23" -tc 0:20 -mps 40 -xponder
#-debug

