#!/bin/bash

dir=$(readlink -f $(dirname $0)/../)

/usr/games/xboard -fcp "$dir/bin/weini --xboard -l"  -fd "$dir" -scp "/media/BK1/www/p/chessEngine/weini/other/Zevra/bin/Linux/zevra_popcnt"  -sd "/media/BK1/www/p/chessEngine/weini/other/Zevra/bin/Linux" -tc 0:20 -mps 40 -sUCI
#-debug

